 
os:
  - linux

dist:
- xenial


language: java
jdk:
- openjdk7
- openjdk8
- openjdk10
- openjdk11
- openjdk12
- oraclejdk8
- oraclejdk11

# prevent travis running gradle assemble; let the build script do it anyway
install: true

# running in container causes test failures and 2x-3x longer build, use standalone instances
sudo: required

# script for build and release via Travis to Bintray
script: gradle/buildViaTravis.sh
